In [1]:
import pandas as pd

In [9]:
fuel = pd.read_csv(r'D:\Portfolio Projects\Public Transit Ridership\Data\RAW_Data\1810000101_FuelPrice(2007-2025)_databaseLoadingData.csv')
fuel.head()

,REF_DATE,GEO,DGUID,Type of fuel,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2007-01,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,87.1,NaN,NaN,NaN,1
1,2007-02,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,91.0,NaN,NaN,NaN,1
2,2007-03,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,102.4,NaN,NaN,NaN,1
3,2007-04,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,105.2,NaN,NaN,NaN,1
4,2007-05,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,111.5,NaN,NaN,NaN,1

In [10]:
fuel = fuel.copy()

# convert REF_DATE to proper monthly date
fuel["date"] = pd.to_datetime(fuel["REF_DATE"], format="%Y-%m")

# force month-start timestamp format
fuel["date"] = fuel["date"].dt.to_period("M").dt.to_timestamp()

print(fuel[["REF_DATE", "date"]].head())
print(fuel["date"].dtype)

  REF_DATE       date
0  2007-01 2007-01-01
1  2007-02 2007-02-01
2  2007-03 2007-03-01
3  2007-04 2007-04-01
4  2007-05 2007-05-01
datetime64[ns]

In [11]:
fuel_clean = fuel[fuel['GEO']=='Toronto, Ontario']
fuel_clean = fuel_clean[['date' , 'VALUE']]

In [12]:
fuel_clean = fuel_clean.rename(columns= {'VALUE' : 'gas_price_regular'})

In [13]:
fuel_clean = fuel_clean.sort_values('date').reset_index(drop=True)

In [14]:
fuel_clean.head()

        date  gas_price_regular
0 2007-01-01               80.1
1 2007-02-01               89.3
2 2007-03-01              101.1
3 2007-04-01              101.1
4 2007-05-01              105.5

In [16]:
fuel_clean.to_csv(r'D:\Portfolio Projects\Public Transit Ridership\Data\Interim\fuelprice_clean.csv')