In [1]:
import pandas as pd

In [2]:
unemp = pd.read_csv(r"D:\Portfolio Projects\Public Transit Ridership\Data\RAW_Data\1410045901_Unemployment(2011-2025)_databaseLoadingData.csv")
unemp.head()

,REF_DATE,GEO,DGUID,Labour force characteristics,Statistics,Data type,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2011-01,Canada,2021A000011124,Unemployment rate,Estimate,Seasonally adjusted,Percent,239,units,0,v1643277934,1.5.1.1,7.8,NaN,NaN,NaN,1
1,2011-02,Canada,2021A000011124,Unemployment rate,Estimate,Seasonally adjusted,Percent,239,units,0,v1643277934,1.5.1.1,7.8,NaN,NaN,NaN,1
2,2011-03,Canada,2021A000011124,Unemployment rate,Estimate,Seasonally adjusted,Percent,239,units,0,v1643277934,1.5.1.1,7.8,NaN,NaN,NaN,1
3,2011-04,Canada,2021A000011124,Unemployment rate,Estimate,Seasonally adjusted,Percent,239,units,0,v1643277934,1.5.1.1,7.8,NaN,NaN,NaN,1
4,2011-05,Canada,2021A000011124,Unemployment rate,Estimate,Seasonally adjusted,Percent,239,units,0,v1643277934,1.5.1.1,7.8,NaN,NaN,NaN,1

In [3]:
unemp.dtypes

REF_DATE                         object
GEO                              object
DGUID                            object
Labour force characteristics     object
Statistics                       object
Data type                        object
UOM                              object
UOM_ID                            int64
SCALAR_FACTOR                    object
SCALAR_ID                         int64
VECTOR                           object
COORDINATE                       object
VALUE                           float64
STATUS                          float64
SYMBOL                          float64
TERMINATED                      float64
DECIMALS                          int64
dtype: object

In [4]:
unemp = unemp.copy()

# convert REF_DATE to proper monthly date
unemp["date"] = pd.to_datetime(unemp["REF_DATE"], format="%Y-%m")

# force month-start timestamp format
unemp["date"] = unemp["date"].dt.to_period("M").dt.to_timestamp()

print(unemp[["REF_DATE", "date"]].head())
print(unemp["date"].dtype)

  REF_DATE       date
0  2011-01 2011-01-01
1  2011-02 2011-02-01
2  2011-03 2011-03-01
3  2011-04 2011-04-01
4  2011-05 2011-05-01
datetime64[ns]

In [5]:
unemp_clean = unemp[['date' , 'GEO' , 'VALUE']]

In [6]:
unemp_clean.head()

        date     GEO  VALUE
0 2011-01-01  Canada    7.8
1 2011-02-01  Canada    7.8
2 2011-03-01  Canada    7.8
3 2011-04-01  Canada    7.8
4 2011-05-01  Canada    7.8

In [7]:
unemp_clean = unemp_clean[unemp_clean['GEO']=='Toronto, Ontario'].copy()

In [8]:
unemp_clean = unemp_clean.rename(columns= {'VALUE' : 'Unemployment Rate'})
unemp_clean = unemp_clean.sort_values('date').reset_index(drop=True)
unemp_clean.head()

        date               GEO  Unemployment Rate
0 2011-01-01  Toronto, Ontario                8.4
1 2011-02-01  Toronto, Ontario                8.5
2 2011-03-01  Toronto, Ontario                8.8
3 2011-04-01  Toronto, Ontario                9.0
4 2011-05-01  Toronto, Ontario                9.1

In [9]:
unemp_clean.to_csv(r"D:\Portfolio Projects\Public Transit Ridership\Data\Interim\unemployment_clean.csv", index=False)